services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker-compose/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
