spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:chai}
    password: ${DATASOURCE_PASSWORD:chai}
  flyway:
    enabled: true
